# Generated by Django 3.1.2 on 2020-11-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('OfficeCode', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('OfficeName', models.CharField(max_length=24)),
                ('Attribution', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('OrgCode', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('OrgName', models.CharField(max_length=24)),
                ('Description', models.CharField(max_length=100)),
                ('DateJoined', models.DateField()),
                ('Address1', models.CharField(max_length=100)),
                ('Address2', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=24)),
                ('State', models.CharField(max_length=24)),
                ('Zipcode', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceCode', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=24)),
                ('Description', models.CharField(max_length=100)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=30)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('SubscriberID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('SubRequestDate', models.DateField()),
                ('SubStartDate', models.DateField()),
                ('SubEndDate', models.DateField()),
                ('Cancellation', models.CharField(max_length=24)),
                ('ServiceCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('SubTypeCode', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('SubTypeName', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('Username', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=24)),
                ('FirstName', models.CharField(max_length=24)),
                ('MiddleName', models.CharField(max_length=24)),
                ('LastName', models.CharField(max_length=24)),
                ('Gender', models.CharField(max_length=24)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=24)),
                ('State', models.CharField(max_length=24)),
                ('ZipCiode', models.CharField(max_length=24)),
                ('Email', models.CharField(max_length=24)),
                ('CellPhone', models.CharField(max_length=24)),
                ('Citizenship', models.CharField(max_length=24)),
                ('DateOfBirth', models.DateField()),
                ('Organization', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('TransferID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('TransferTo', models.CharField(max_length=24)),
                ('RequestDate', models.DateField()),
                ('TransferDate', models.DateField()),
                ('SubscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='SubTypeCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo'),
        ),
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberStartDate', models.DateField()),
                ('MemberEndDate', models.DateField()),
                ('NativeCountry', models.CharField(max_length=24)),
                ('Citizenship', models.CharField(max_length=24)),
                ('isDelegate', models.CharField(max_length=24)),
                ('OrgCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organization')),
                ('SubscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('OfficeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.office')),
                ('SubscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
    ]
